title: Hello, world! I'm Ryan Cox
description: > # this means to ignore newlines until "baseurl:"
  A personal website to house my technical ramblings about software testing, REST API automation, UI automation, and general programming and testing ah-ha's.
permalink: ':title/'
baseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog
url: "rycox.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Ryan Cox
author-img: ryan-cox.jpg # add your photo
about-author: I am a software tester, living my best life automating service-side testing and dabbling in UI automation when I have to.
social-twitter: coxrya
social-github: RyCox
social-linkedin: ryan-cox-44925749/

# Disqus
discus-identifier: disqus_Cf9zJFfSZE # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
